  name: Push on Branch
  on: [ push ]
  jobs:
    project-build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Set up JDK 20.0.2+9
          uses: actions/setup-java@v3
          with:
            java-version: '20.0.2+9'
            distribution: 'adopt'

        - name: Set up the Maven dependencies caching
          uses: actions/cache@v3
          with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2

        - name: Install Maven dependencies
          run: mvn install

        - name: Run tests
          run: mvn --batch-mode --update-snapshots test

        - name: Run build
          run: mvn install